services:
  frontend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  # 如果需要添加后端服务，可以取消注释以下内容并进行相应配置
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network

  # database:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: order_ease
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: